### ISSUE TITLE
when available in IMU data

### ISSUE THREAD

**Issue by sjko** [stereolabs/zedxone-ros2#2]
I plan to use ZED X One camera for a project. I heard that obtaining IMU data is not yet supported. Could you please let me know when this feature will be available?

**Comment by Myzhar** [comment]
This repository uses the library in https://github.com/stereolabs/zedx-one-capture to communicate with the camera.
The library does not provide an IMU interface yet and I'm not sure it's a feature that will be made available because we are soon adding support to the ZED X One directly into the ZED SDK.

**Comment by beniaminopozzan** [comment]
Hi @Myzhar , is there a timeline regarding adding support to the ZED X One directly into the ZED SDK? Thanks!

**Comment by Myzhar** [comment]
It will be in the ZED SDK v4.2 that will be released soon. 
There's not yet a fixed date for the release.

**Comment by sezarxray** [comment]
first build product then sell it plz...

**Comment by Myzhar** [comment]
Please wait a few weeks for the release of ZED SDK v4.2. It will provide full monocular camera integration, eliminating the need for this library when using a standalone ZED X One device.
